### ISSUE TITLE
Task group waits for each task, sequentially

### ISSUE THREAD

**Issue by gerardolima** [privatenumber/tasuku#26]
## Bug description
When checking `tasuku` in the playground, I noticed a single task group with 3 tasks of 1 second each takes 3 seconds, when I expected that it should complete after just over 1 second.

![image](https://github.com/privatenumber/tasuku/assets/4498885/9c196c3d-20a8-4cc0-bdcf-ade4c2e5344c)

## Reproduction
The code is available in the playground https://stackblitz.com/edit/tasuku-demo-vwyx8w?file=index.js

## Environment

- tasuku version: ^1.0.0
- Operating System: node
- Node version: v18.18.0
- Package manager (npm/yarn/pnpm) and version: 10.2.3

**Comment by privatenumber** [comment]
Expected behavior. I think what you want is this: https://github.com/privatenumber/tasuku#running-tasks-in-parallel
